@startuml

rectangle "Сфомитрован запрос об изменении" as ReportCreated
rectangle "Запрос об изменении согласован" as ReportAccepted
rectangle "Запрос об изменении не принят" as ReportRejected
rectangle "Сфомитрована модификация" as ModificationRequestCreated
rectangle "Модификация проанализирована" as ModificationAnalysisDone
rectangle "Модификация принята" as ModificationAccepted
rectangle "Модификация не принята" as ModificationRejected
rectangle "Модификация требует исправлений" as ModificationMustBeImproved


ReportCreated --> ReportRejected
ReportCreated --> ReportAccepted
ReportAccepted .DOWN.> ModificationRequestCreated
ModificationRequestCreated -DOWN-> ModificationAnalysisDone
ModificationAnalysisDone -DOWN-> ModificationAccepted
ModificationAnalysisDone -DOWN-> ModificationRejected
ModificationAnalysisDone -LEFT-> ModificationMustBeImproved
ModificationMustBeImproved -> ModificationRequestCreated

note left of ReportCreated #green: "Запрос об улучшении"
note right of ReportCreated #red: "Отчет об ошибке"
note right of ModificationRequestCreated #yellow: "Описание модификации"

note right of ModificationAnalysisDone #brown: "Отчет об анализе модификации"
@enduml